# Enhanced Combined Drought Index - Soil Moisture Drought Index

**Keywords**: :index:`data used; WAPOR`, :index:`climate`, :index:`soil moisture`;

## Background

Drought is an extended period, during which, fresh water availability and accessibility for the ecosystem at a given time and place is below normal, due to unfavourable spatial and temporal distribution of rainfall, temperature, soil moisture and wind characteristics [(Balint et al., 2013)](https://doi.org/10.1016/B978-0-444-59559-1.00023-2). Severe droughts can affect large populations, leading to a long-term threat to people’s livelihoods and result in tremendous economic loss [(Enenkel et al., 2016)](https://doi.org/10.3390/rs8040340).

The Enhanced Combined Drought Index aims at the timely and reliable detection of drought events with regard to their spatio-temporal extent and severity. The Enhanced Drought Index is a combination of the following: a precipitation component, which considers rainfall deficits and dryness persistence; a soil moisture component, which considers soil moisture deficits and deficit persistence; a vegetation component which considers NDVI deficits and deficit persistence; and a temperature component, which considers temperature excesses and persistence of high temperatures. The index uses satellite-derived rainfall, soil moisture, land surface temperature and vegetation status as input datasets. [(Enenkel et al., 2016)](https://doi.org/10.3390/rs8040340)

The drought index calculated using the precipitation component is referred as the **Precipitation Drought Index (PDI)**, while the index based on temperature is named as **Temperature Drought Index (TDI)**, the index based on soil moisture is named as the **Soil Moisture Drought Index** and that based on the vegetation component is named as **Vegetation Drought Index (VDI)**.

Each drought index can be expressed as:

$\text{Drought Index} = \frac{\text{Actual Average for Interest Period}}{\text{Long Term Average for Interest Period}} * \sqrt{\frac{\text{Actual Length of Continuous Deficit or Excess in the Interest Period}}{\text{Long Term Average of Continuous Deficit or Excess in the Interest Period}}}$

Each drought index is calculated similarly. The equation below illustrates the calculation of the ECDI precipitation component:

\begin{equation}
\text{PDI}_{y,d} = \frac{
\frac{1}{\text{IP}} \sum_{j=0}^{\text{IP} - 1} P^*_{y,(d-j)}}{\frac{1}{n}\sum_{k=1}^n[\frac{1}{\text{IP}} \sum_{j=0}^{\text{IP} - 1} P^*_{(d-j), k}]} * \sqrt{\frac{(\text{RL}^*)P^*_{d, y}}{\frac{1}{n}\sum_{k=1}^{n}(\text{RL}^*)P^*_{d, k}}}
\end{equation}

- $\text{PDI}_{y,d}$ is the Precipitation Drought Index for year $\text{y}$ and time unit (dekad/month) $\text{d}$

- $P^*$ is the modified dekadal/monthly precipitation average 

- $\text{RL}*$ is the modified run length parameter 

- $\text{RL*}(P*)$ (run length) is the maximum number of successive dekads/months below the long-term average rainfall in the interest period
> **Note**: For temperature, run length is the maximum number of successive dekads/months above the long-term average temperature in the interest period

- $\text{IP}$ is the interest period (e.g. 3, 4, 5, . . . dekads/months) (longer IPs detect more severe drought events). IP is flexible defines to what extent past observations are considered.

- $n$ is the number of years where relevant data are available,

- $j$ is the summation running parameter covering the Interest Period

- $k$ is the summation parameter covering the years where relevant data are available

- $d$ time unit (dekad or month) 

- $y$ year

The raw time series of temperature and precipitation as well as the run length are modified to adjust the range of all variables and to avoid a division by zero.

\begin{equation}
T^* = (T_{max} + 1) - T
\end{equation}

\begin{equation}
P^* = P + 1
\end{equation}

\begin{equation}
\text{RL}^* = (\text{RL}_{max} + 1) - \text{RL}
\end{equation}

\begin{equation}
\text{NDVI}^* = \text{NDVI} - (\text{NDVI}_{min} -0.01)
\end{equation}


- $T^*$ is the modified dekadal/monthly temperature average 
- $P^*$ is the modified dekadal/monthly precipitation average 
- $\text{RL}^*$ is the modified run length

All the individual drought indices differ in range. To improve their interpretability and visual comparability a simple scaling factor is introduced.

\begin{equation}
PDI_{scaled} = \frac{(PDI - PDI_{min})}{(PDI_{max} - PDI_{min})}
\end{equation}

            ,
The weight of each individual drought index is automatically calculated for every grid point (pixel) with respect to its capability to reflect the future vegetation status (NDVI) and multiplied by the respective individual index to calculate the ECDI. In the case of data gaps in one input dataset, the weights are automatically redistributed to other available variables.

\begin{equation}
ECDI = \sum_{i-1}^{n}w_{i} * \text{DI}_{i}
\end{equation}

- $ECDI$ Enhanced Combined Drought Index 

- $w$ Weight for each individual drought index (e.g., rainfall)

- $\text{DI}$ Individual drought index 

- $n$ number of drought indices used to calculate the ECDI 

- $i$ running parameter covering the number of drought indices

\begin{equation}
w_{i} = \frac{\frac{lag^*_{i}}{\sum_{j=1}^{n} lag^*_{j}} + \frac{corr^*_{i}}{\sum_{j=1}^{n} corr^*_{j}}}{2}
\end{equation}

- $w$ weight for the respective drought index 

- $lag^*$ modified time lag for the respective parameter 

- $corr^*$ modified correlation coefficient for the respective parameter 

- $i$ index for the respective parameter/drought index 

- $j$ running parameter covering all parameters used for the ECDI calculation

- $n$ number of individual drought indices used for the ECDI calculation


The notebook outlines:

***

## Getting started

To run this analysis, run all the cells in the notebook, starting with the "Load packages" cell.

### Load packages

In [ ]:
import calendar
import json
import os
from datetime import datetime, timedelta

import dask
import geopandas as gpd
import numpy as np
import pandas as pd
import rioxarray
import toolz
import xarray as xr
from datacube import Datacube
from deafrica_tools.bandindices import calculate_indices
from deafrica_tools.dask import create_local_dask_cluster
from deafrica_tools.datahandling import load_ard
from deafrica_tools.load_wapor import get_all_WaPORv3_mapsets, get_WaPORv3_info, load_wapor_ds
from odc.geo.geobox import GeoBox
from odc.geo.geom import Geometry
from pyarrow import Table
from pyarrow.parquet import write_table
from wapordl import wapor_map
from xarray.core.groupby import DataArrayGroupBy, DatasetGroupBy

### Set up a Dask cluster

Dask can be used to better manage memory use and conduct the analysis in parallel. 
For an introduction to using Dask with Digital Earth Africa, see the [Dask notebook](../../Beginners_guide/08_Parallel_processing_with_dask.ipynb).

>**Note**: We recommend opening the Dask processing window to view the different computations that are being executed; to do this, see the *Dask dashboard in DE Africa* section of the [Dask notebook](../../Beginners_guide/08_Parallel_processing_with_dask.ipynb).

To use Dask, set up the local computing cluster using the cell below.

In [2]:
create_local_dask_cluster()

/usr/local/lib/python3.10/dist-packages/distributed/node.py:182: UserWarning: Port 8787 is already in use.
Perhaps you already have a cluster running?
Hosting the HTTP server on port 35417 instead
  warnings.warn(
INFO: State start
INFO:   Scheduler at:     tcp://127.0.0.1:33641
INFO:   dashboard at:           127.0.0.1:35417
INFO:         Start Nanny at: 'tcp://127.0.0.1:37295'
INFO: Register worker <WorkerState 'tcp://127.0.0.1:37963', name: 0, status: init, memory: 0, processing: 0>
INFO: Starting worker compute stream, tcp://127.0.0.1:37963
INFO: Starting established connection to tcp://127.0.0.1:53414
INFO: Receive client connection: Client-d2cb5dcd-1f95-11ef-8554-bea72aca40b5
INFO: Starting established connection to tcp://127.0.0.1:53416

### Analysis parameters

The following cell sets important parameters for the analysis:

* `country`: The country to run the analysis over.
* `resolution`: The x and y cell resolution of the satellite data in metres (spatial resolution). We'll use 5,000 m, which is approximately equal to the default CHIRPS resolution.
* `output_crs` : The coordinate reference system that the loaded data is to be reprojected to.
* `dask_chunks`:  the size of the dask chunks, dask breaks data into manageable chunks that can be easily stored in memory, e.g. `dict(x=1000,y=1000)`
* `time_range` : Time range to load data for.
* `ip` : The interest period to use to calculate the drought indices e.g. (3, 4, 5 dekads). It defines to what extent past observations are considered. Longer IPs detect more severe drought events. For example, if the IP=3 dekads, then the drought index (say PDI) of 0.35 for dekad 2 of 2006 implies actual drought for dekad 36 of 2005, dekad 1 of 2006 and dekad 2 of 2006.
* `output_dir` :  The directory in which to store results from the analysis.

**If running the notebook for the first time**, keep the default settings below.
This will demonstrate how the analysis works and provide meaningful results.

In [3]:
resolution = (-5000, 5000)
output_crs = "EPSG:6933"
dask_chunks = dict(x=3200,y=3200)
time_range = ("2014-01-01", "2024-12-31")
output_dir = "results"
# Corresponding to the six-months Standardized Precipitation Evapotranspiration Index
ip = 18

In [4]:
# Create the outpur directory if it does not exist.
os.makedirs(output_dir, exist_ok=True)

In [5]:
african_countries_url = "https://raw.githubusercontent.com/digitalearthafrica/deafrica-sandbox-notebooks/main/Supplementary_data/Rainfall_anomaly_CHIRPS/african_countries.geojson"
african_countries = gpd.read_file(african_countries_url)
print(np.unique(african_countries.COUNTRY))

In [ ]:
# Load the area of interest
country = "Ethiopia"

idx = african_countries[african_countries['COUNTRY'] == country].index[0]
geopolygon = Geometry(geom=african_countries.iloc[idx].geometry, crs=african_countries.crs)

In [6]:
# Create the output path
output_path = os.path.join(output_dir, f"SMDI_{country}.parquet")

## Load WaPOR soil moisture data
Load the WaPOR soil moisture data using the analysis parameters set in the previous section.

In [7]:
# List all available WAPOR datasets.
get_all_WaPORv3_mapsets()

       Mapset Code                                 Mapset Description
0        L1-AETI-A  Actual EvapoTranspiration and Interception (Gl...
1        L1-AETI-D  Actual EvapoTranspiration and Interception (Gl...
2        L1-AETI-M  Actual EvapoTranspiration and Interception (Gl...
3           L1-E-A               Evaporation (Global - Annual - 300m)
4           L1-E-D              Evaporation (Global - Dekadal - 300m)
5        L1-GBWP-A   Gross biomass water productivity (Annual - 300m)
6           L1-I-A              Interception (Global - Annual - 300m)
7           L1-I-D             Interception (Global - Dekadal - 300m)
8        L1-NBWP-A     Net biomass water productivity (Annual - 300m)
9         L1-NPP-D   Net Primary Production (Global - Dekadal - 300m)
10        L1-NPP-M   Net Primary Production (Global - Monthly - 300m)
11        L1-PCP-A  Precipitation (Global - Annual - Approximately...
12        L1-PCP-D  Precipitation (Global - Dekadal - Approximatel...
13        L1-PCP-E  Precipitation (Global - Daily - Approximately ...
14        L1-PCP-M  Precipitation (Global - Monthly - Approximatel...
15   L1-QUAL-LST-D  Quality land surface temperature (Global - Dek...
16  L1-QUAL-NDVI-D  Quality of Normalized Difference Vegetation In...
17        L1-RET-A  Reference Evapotranspiration (Global - Annual ...
18        L1-RET-D  Reference Evapotranspiration (Global - Dekadal...
19        L1-RET-E  Reference Evapotranspiration (Global - Daily -...
20        L1-RET-M  Reference Evapotranspiration (Global - Monthly...
21        L1-RSM-D   Relative Soil Moisture (Global - Dekadal - 300m)
22          L1-T-A             Transpiration (Global - Annual - 300m)
23          L1-T-D            Transpiration (Global - Dekadal - 300m)
24        L1-TBP-A  Total Biomass Production (Global - Annual - 300m)
25       L2-AETI-A  Actual EvapoTranspiration and Interception (Na...
26       L2-AETI-D  Actual EvapoTranspiration and Interception (Na...
27       L2-AETI-M  Actual EvapoTranspiration and Interception (Na...
28          L2-E-A             Evaporation (National - Annual - 100m)
29          L2-E-D            Evaporation (National - Dekadal - 100m)
30       L2-GBWP-A   Gross biomass water productivity (Annual - 100m)
31          L2-I-A            Interception (National - Annual - 100m)
32          L2-I-D           Interception (National - Dekadal - 100m)
33       L2-NBWP-A     Net biomass water productivity (Annual - 100m)
34        L2-NPP-D  Net Primary Production (National - Dekadal - 1...
35        L2-NPP-M  Net Primary Production (National - Monthly - 1...
36  L2-QUAL-NDVI-D  Quality of normalized difference vegetation in...
37        L2-RSM-D  Relative Soil Moisture (National - Dekadal - 1...
38          L2-T-A           Transpiration (National - Annual - 100m)
39          L2-T-D          Transpiration (National - Dekadal - 100m)
40        L2-TBP-A  Total Biomass Production (Global - Annual - 100m)

In [8]:
# Select the Soil Moisture variable
variable = "L2-RSM-D"

In [9]:
# Get the bounding box of the area of interest.
region = [*geopolygon.boundingbox]

In [10]:
# Folder to store the downloaded wapor data in.
download_folder = os.path.join("WaPOR_v3", variable)
os.makedirs(download_folder, exist_ok=True)

In [11]:
%%time
# Download the required netcdf files to disk.
# Takes about 3hrs 45min on the 100GB sandbox.
# The nc_fp object is the file path to the stored netCDF
nc_fp = wapor_map(region=region, variable=variable, period=time_range, folder=download_folder, extension=".nc")

CPU times: user 5 µs, sys: 0 ns, total: 5 µs
Wall time: 8.82 µs

In [13]:
# Load the netCDF or TIF file downloaded.
ds_sm_dekadal = load_wapor_ds(filename=nc_fp, variable=variable).rename({'time': 'dekad'})
ds_sm_dekadal

<xarray.Dataset>
Dimensions:      (x: 990, y: 1906, dekad: 230)
Coordinates:
  * x            (x) float64 35.52 35.52 35.53 35.53 ... 36.49 36.49 36.49 36.49
  * y            (y) float64 1.655 1.654 1.653 1.652 ... -0.2036 -0.2046 -0.2056
    spatial_ref  int32 4326
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11
Data variables:
    L2-RSM-D     (dekad, y, x) int16 624 672 746 840 856 ... 578 574 560 616 561
Attributes: (12/17)
    lat#long_name:        latitude
    lat#standard_name:    latitude
    lat#units:            degrees_north
    lon#long_name:        longitude
    lon#standard_name:    longitude
    lon#units:            degrees_east
    ...                   ...
    overview:             NONE
    scale_factor:         0.001
    temporal_resolution:  Dekad
    units:                %
    _FillValue:           -9999
    add_offset:           0.0

In [14]:
# Create a geobox to use to reproject the data.
geobox = GeoBox.from_geopolygon(geopolygon=geopolygon, resolution=abs(resolution[0]), crs=output_crs)

# Reproject using the geobox
ds_sm_dekadal = ds_sm_dekadal.odc.reproject(how=geobox)
ds_sm_dekadal

<xarray.Dataset>
Dimensions:      (dekad: 230, y: 49, x: 20)
Coordinates:
    spatial_ref  int32 6933
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11
  * y            (y) float64 2.125e+05 2.075e+05 ... -2.25e+04 -2.75e+04
  * x            (x) float64 3.428e+06 3.432e+06 ... 3.518e+06 3.522e+06
Data variables:
    L2-RSM-D     (dekad, y, x) int16 -9999 -9999 -9999 ... -9999 -9999 -9999

In [ ]:
# Rasterize the country geopolygon and mask the loaded data.
country_mask = rasterize(poly=geopolygon, how=ds_sm_dekadal.odc.geobox)
ds_sm_dekadal = ds_sm_dekadal.where(country_mask)

In [15]:
# To DataArray
da_sm_dekadal = ds_sm_dekadal[variable]
da_sm_dekadal

<xarray.DataArray 'L2-RSM-D' (dekad: 230, y: 49, x: 20)>
array([[[-9999, -9999, -9999, ..., -9999, -9999, -9999],
        [-9999,   549,   552, ...,   263,   161, -9999],
        [-9999,   528,   439, ...,   168,   240, -9999],
        ...,
        [-9999,   581,   688, ...,   781,   583, -9999],
        [-9999,   586,   508, ...,   519,   710, -9999],
        [-9999, -9999, -9999, ..., -9999, -9999, -9999]],

       [[-9999, -9999, -9999, ..., -9999, -9999, -9999],
        [-9999,   530,   531, ...,   263,   175, -9999],
        [-9999,   511,   405, ...,   177,   252, -9999],
        ...,
        [-9999,   568,   678, ...,   750,   549, -9999],
        [-9999,   561,   479, ...,   497,   644, -9999],
        [-9999, -9999, -9999, ..., -9999, -9999, -9999]],

       [[-9999, -9999, -9999, ..., -9999, -9999, -9999],
        [-9999,   491,   499, ...,   233,   146, -9999],
        [-9999,   487,   365, ...,   153,   207, -9999],
        ...,
...
        ...,
        [-9999,   870,   998, ...,   786,   763, -9999],
        [-9999,   804,   804, ...,   703,   762, -9999],
        [-9999, -9999, -9999, ..., -9999, -9999, -9999]],

       [[-9999, -9999, -9999, ..., -9999, -9999, -9999],
        [-9999,   572,   737, ...,   381,   467, -9999],
        [-9999,   629,   550, ...,   356,   423, -9999],
        ...,
        [-9999,   804,   809, ...,   897,   841, -9999],
        [-9999,   648,   649, ...,   790,   832, -9999],
        [-9999, -9999, -9999, ..., -9999, -9999, -9999]],

       [[-9999, -9999, -9999, ..., -9999, -9999, -9999],
        [-9999,   570,   629, ...,   279,   211, -9999],
        [-9999,   611,   377, ...,   209,   284, -9999],
        ...,
        [-9999,   718,   763, ...,   573,   586, -9999],
        [-9999,   666,   634, ...,   602,   717, -9999],
        [-9999, -9999, -9999, ..., -9999, -9999, -9999]]], dtype=int16)
Coordinates:
    spatial_ref  int32 6933
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11
  * y            (y) float64 2.125e+05 2.075e+05 ... -2.25e+04 -2.75e+04
  * x            (x) float64 3.428e+06 3.432e+06 ... 3.518e+06 3.522e+06
Attributes: (12/18)
    lat#long_name:        latitude
    lat#standard_name:    latitude
    lat#units:            degrees_north
    lon#long_name:        longitude
    lon#standard_name:    longitude
    lon#units:            degrees_east
    ...                   ...
    scale_factor:         0.001
    temporal_resolution:  Dekad
    units:                %
    _FillValue:           -9999
    add_offset:           0.0
    nodata:               -9999

In [16]:
# Set -9999 no-data values to NaN
da_sm_dekadal = da_sm_dekadal.where(da_sm_dekadal != da_sm_dekadal.attrs["nodata"])

da_sm_dekadal

<xarray.DataArray 'L2-RSM-D' (dekad: 230, y: 49, x: 20)>
array([[[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan, 549., 552., ..., 263., 161.,  nan],
        [ nan, 528., 439., ..., 168., 240.,  nan],
        ...,
        [ nan, 581., 688., ..., 781., 583.,  nan],
        [ nan, 586., 508., ..., 519., 710.,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan, 530., 531., ..., 263., 175.,  nan],
        [ nan, 511., 405., ..., 177., 252.,  nan],
        ...,
        [ nan, 568., 678., ..., 750., 549.,  nan],
        [ nan, 561., 479., ..., 497., 644.,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan, 491., 499., ..., 233., 146.,  nan],
        [ nan, 487., 365., ..., 153., 207.,  nan],
        ...,
...
        ...,
        [ nan, 870., 998., ..., 786., 763.,  nan],
        [ nan, 804., 804., ..., 703., 762.,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan, 572., 737., ..., 381., 467.,  nan],
        [ nan, 629., 550., ..., 356., 423.,  nan],
        ...,
        [ nan, 804., 809., ..., 897., 841.,  nan],
        [ nan, 648., 649., ..., 790., 832.,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]],

       [[ nan,  nan,  nan, ...,  nan,  nan,  nan],
        [ nan, 570., 629., ..., 279., 211.,  nan],
        [ nan, 611., 377., ..., 209., 284.,  nan],
        ...,
        [ nan, 718., 763., ..., 573., 586.,  nan],
        [ nan, 666., 634., ..., 602., 717.,  nan],
        [ nan,  nan,  nan, ...,  nan,  nan,  nan]]], dtype=float32)
Coordinates:
    spatial_ref  int32 6933
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11
  * y            (y) float64 2.125e+05 2.075e+05 ... -2.25e+04 -2.75e+04
  * x            (x) float64 3.428e+06 3.432e+06 ... 3.518e+06 3.522e+06
Attributes: (12/18)
    lat#long_name:        latitude
    lat#standard_name:    latitude
    lat#units:            degrees_north
    lon#long_name:        longitude
    lon#standard_name:    longitude
    lon#units:            degrees_east
    ...                   ...
    scale_factor:         0.001
    temporal_resolution:  Dekad
    units:                %
    _FillValue:           -9999
    add_offset:           0.0
    nodata:               -9999

## Group the modified timeseries using the `ip` parameter

The `ip` parameter determines to what extent past observations are considered. Longer IPs detect more severe drought events. The default `ip` used of **18 dekads** corresponds to the 6-month Standardized Precipitation Evapotranspiration Index.

For example, calculating the Soil Moisture Drought Index for the dekad `2011-01-11` using an interest period of `ip=3` requires rainfall data from the dekad `2010-12-21`, `2011-01-01` and `2011-01-11`.


**Each interest period is labelled using its end dekad.**

In [17]:
def get_dekad(date: np.datetime64) -> np.datetime64:
    """
    Get the start date of the dekad that a date belongs to.
    Every month has three dekads, such that the first two dekads
    have 10 days (i.e., 1-10, 11-20), and the third is comprised of the
    remaining days of the month.

    Parameters
    ----------
    date : np.datetime64
        Date to check.

    Returns
    -------
    np.datetime64
        Start date of the dekad.
    """
    timestamp = pd.Timestamp(date)
    year = timestamp.year
    month = timestamp.month

    first_day = datetime(year, month, 1)
    last_day = datetime(year, month, calendar.monthrange(year, month)[1])

    d1_start_date, d2_start_date, d3_start_date = pd.date_range(
        start=first_day, end=last_day, freq="10D", inclusive="left"
    )

    if d1_start_date <= timestamp < d2_start_date:
        return np.datetime64(d1_start_date, "ns")
    elif d2_start_date <= timestamp < d3_start_date:
        return np.datetime64(d2_start_date, "ns")
    else:
        return np.datetime64(d3_start_date, "ns")
    

def get_dekad_no_in_month(date: np.datetime64) -> int:
    """
    Get the number of the dekad in a month that a date belongs to.
    Every month has three dekads, such that the first two dekads
    have 10 days (i.e., 1-10, 11-20), and the third is comprised of the
    remaining days of the month.

    Parameters
    ----------
    date : np.datetime64
        Date to check.

    Returns
    -------
    int
        Number of the dekad in a month.
    """
    timestamp = pd.Timestamp(date)
    year = timestamp.year
    month = timestamp.month

    first_day = datetime(year, month, 1)
    last_day = datetime(year, month, calendar.monthrange(year, month)[1])

    d1_start_date, d2_start_date, d3_start_date = pd.date_range(
        start=first_day, end=last_day, freq="10D", inclusive="left"
    )

    if d1_start_date <= timestamp < d2_start_date:
        return 1
    elif d2_start_date <= timestamp < d3_start_date:
        return 2
    else:
        return 3


def get_dekad_no_in_year(date: np.datetime64) -> int:
    """
    Get the number of the dekad in a year that a date belongs to.
    Every month has three dekads, such that the first two dekads
    have 10 days (i.e., 1-10, 11-20), and the third is comprised of the
    remaining days of the month (21-last day). Every year has 36 dekads.

    Parameters
    ----------
    date : np.datetime64
        Date to check.

    Returns
    -------
    int
        Number of the dekad in a year.
    """
    dekad_no_in_month = get_dekad_no_in_month(date=date)
    timestamp = pd.Timestamp(date)
    month = timestamp.month
    dekad_no_in_year = ((month - 1) * 3) + dekad_no_in_month
    return dekad_no_in_year


def get_interest_period(dekad: np.datetime64, ip: int) -> list[np.datetime64]:
    """
    Get all the dekads in the interest period for a dekad.
    `dekad` will always be the end dekad of the interest period.

    Parameters
    ----------
    dekad : np.datetime64
        Dekad to get the interest period for.
        Will always be the end dekad of the interest period
    ip : int
        Number of dekads in an interest period.

    Returns
    -------
    list[np.datetime64]
        All the dekads in the interest period.
    """
    year = pd.Timestamp(dekad).year
    dekad_no_in_year = get_dekad_no_in_year(dekad) - (ip - 1)
    while dekad_no_in_year <= 0:
        year -= 1
        dekad_no_in_year += 36

    month = (dekad_no_in_year - 1) // 3 + 1
    dekad_no_in_month = (dekad_no_in_year - 1) % 3 + 1
    if dekad_no_in_month == 1:
        day = 1
    elif dekad_no_in_month == 2:
        day = 11
    elif dekad_no_in_month == 3:
        day = 21

    start_dekad = np.datetime64(datetime(year, month, day), "ns")
    date_range = pd.date_range(
        start_dekad, dekad, freq=timedelta(days=1), inclusive="both"
    ).values
    interest_period_dekads = np.unique(np.vectorize(get_dekad)(date_range))
    return interest_period_dekads


def bin_by_interest_period(
    ds: xr.Dataset | xr.DataArray, ip: int
) -> dict[np.datetime64, xr.Dataset | xr.DataArray]:
    """
    Bin each dekad in the dataset by interest period.

    Parameters
    ----------
    ds : xr.Dataset | xr.DataArray
        Dataset to bin
    ip : int
        Number of dekads in an interest period.

    Returns
    -------
    list[tuple[np.datetime64, np.datetime64]]
        List of dekad ranges to bin
    """
    start_date = ds.dekad.min().values
    end_date = ds.dekad.max().values
    date_range = pd.date_range(
        start_date, end_date, freq=timedelta(days=1), inclusive="both"
    ).values
    dekads = np.unique(np.vectorize(get_dekad)(date_range))
    bins = {i: get_interest_period(dekad=i, ip=ip) for i in dekads}
    binned_by_interest_period = {interest_period_label : ds.reindex(dekad=interest_period) for interest_period_label, interest_period in bins.items()}
    return binned_by_interest_period

In [18]:
# Group the soil moisture dekadal timeseries by the interest period.
# The dictionary keys are the end dekad for each interest period.
# The values of the dictionary are the soil moisture data that belongs to the interest period
da_sm_binned_by_interest_period = bin_by_interest_period(ds=da_sm_dekadal, ip=ip)

In [19]:
# Get the interest periods
interest_periods = list(da_sm_binned_by_interest_period.keys())

## Get the average values for each interest period

Get the actual average soil moisture for each interest period.

In [20]:
da_sm_actual_avg_for_ip = xr.concat([da_sm_binned_by_interest_period[i].mean(dim="dekad").assign_coords(dekad=i).expand_dims({"dekad": 1}) for i in interest_periods], dim="dekad")
da_sm_actual_avg_for_ip

<xarray.DataArray 'L2-RSM-D' (dekad: 230, y: 49, x: 20)>
array([[[      nan,       nan,       nan, ...,       nan,       nan,
               nan],
        [      nan, 549.     , 552.     , ..., 263.     , 161.     ,
               nan],
        [      nan, 528.     , 439.     , ..., 168.     , 240.     ,
               nan],
        ...,
        [      nan, 581.     , 688.     , ..., 781.     , 583.     ,
               nan],
        [      nan, 586.     , 508.     , ..., 519.     , 710.     ,
               nan],
        [      nan,       nan,       nan, ...,       nan,       nan,
               nan]],

       [[      nan,       nan,       nan, ...,       nan,       nan,
               nan],
        [      nan, 539.5    , 541.5    , ..., 263.     , 168.     ,
               nan],
        [      nan, 519.5    , 422.     , ..., 172.5    , 246.     ,
               nan],
...
        [      nan, 710.6111 , 866.55554, ..., 692.05554, 589.2222 ,
               nan],
        [      nan, 691.3889 , 693.5    , ..., 569.1111 , 616.7778 ,
               nan],
        [      nan,       nan,       nan, ...,       nan,       nan,
               nan]],

       [[      nan,       nan,       nan, ...,       nan,       nan,
               nan],
        [      nan, 482.94446, 536.8889 , ..., 284.1111 , 203.88889,
               nan],
        [      nan, 508.94446, 393.94446, ..., 205.     , 249.     ,
               nan],
        ...,
        [      nan, 705.2778 , 861.8333 , ..., 678.6667 , 584.     ,
               nan],
        [      nan, 685.7778 , 686.3333 , ..., 560.1111 , 613.1667 ,
               nan],
        [      nan,       nan,       nan, ...,       nan,       nan,
               nan]]], dtype=float32)
Coordinates:
  * y            (y) float64 2.125e+05 2.075e+05 ... -2.25e+04 -2.75e+04
  * x            (x) float64 3.428e+06 3.432e+06 ... 3.518e+06 3.522e+06
    spatial_ref  int32 6933
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11

## Get the long term average for each interest period over the years of available data

In [21]:
# Group the interest periods by year by getting the dekad number in the year for the end dekad of
# the interest period. 
grouped_by_year = toolz.groupby(lambda dekad: get_dekad_no_in_year(date=dekad), interest_periods)

Get the long term average soil moisture for each interest period.

In [22]:
long_term_avg_sm = {}
for dekad_no_in_year, interest_periods_list in grouped_by_year.items():
    long_term_avg_for_period = xr.concat([da_sm_binned_by_interest_period[i] for i in interest_periods_list], dim="dekad").mean(dim="dekad")
    long_term_avg_sm[dekad_no_in_year] = long_term_avg_for_period
    
da_sm_long_term_avg_for_ip = xr.concat([long_term_avg_sm[get_dekad_no_in_year(i)].assign_coords(dekad=i).expand_dims({"dekad": 1}) for  i in interest_periods], dim="dekad")

assert all(da_sm_actual_avg_for_ip.dekad.values == da_sm_long_term_avg_for_ip.dekad.values)

da_sm_long_term_avg_for_ip

<xarray.DataArray 'L2-RSM-D' (dekad: 230, y: 49, x: 20)>
array([[[      nan,       nan,       nan, ...,       nan,       nan,
               nan],
        [      nan, 594.9358 , 596.8257 , ..., 273.83487, 182.27522,
               nan],
        [      nan, 589.6422 , 489.55963, ..., 205.33945, 259.58716,
               nan],
        ...,
        [      nan, 738.13763, 788.63306, ..., 687.2936 , 652.5688 ,
               nan],
        [      nan, 717.63306, 683.6147 , ..., 642.33026, 773.9174 ,
               nan],
        [      nan,       nan,       nan, ...,       nan,       nan,
               nan]],

       [[      nan,       nan,       nan, ...,       nan,       nan,
               nan],
        [      nan, 585.62726, 589.13635, ..., 271.9091 , 179.79091,
               nan],
        [      nan, 581.37274, 483.3    , ..., 202.23636, 255.27272,
               nan],
...
        [      nan, 618.4628 , 740.22314, ..., 615.80164, 562.8678 ,
               nan],
        [      nan, 601.6529 , 592.3884 , ..., 547.3058 , 722.8843 ,
               nan],
        [      nan,       nan,       nan, ...,       nan,       nan,
               nan]],

       [[      nan,       nan,       nan, ...,       nan,       nan,
               nan],
        [      nan, 518.3525 , 540.78687, ..., 253.91803, 164.7295 ,
               nan],
        [      nan, 534.7951 , 432.85245, ..., 181.2623 , 224.04099,
               nan],
        ...,
        [      nan, 613.71313, 736.9016 , ..., 609.13934, 560.4672 ,
               nan],
        [      nan, 596.0738 , 590.0984 , ..., 543.1803 , 717.9672 ,
               nan],
        [      nan,       nan,       nan, ...,       nan,       nan,
               nan]]], dtype=float32)
Coordinates:
  * y            (y) float64 2.125e+05 2.075e+05 ... -2.25e+04 -2.75e+04
  * x            (x) float64 3.428e+06 3.432e+06 ... 3.518e+06 3.522e+06
    spatial_ref  int32 6933
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11

## Get the actual length of continous deficit in each interest period

For soil moisture the run length is the number of successive dekads in an interest period below the long term average for the same interest period.

In [23]:
def get_no_data_mask(arr):
    """
    Check if all values in an array are NaN
    """
    return np.all(np.isnan(arr))

# From https://www.geeksforgeeks.org/maximum-consecutive-ones-or-zeros-in-a-binary-array/
def max_consecutive_ones(arr: np.ndarray) -> int:
    """
    Get the maximum number of successive ones in an array.

    Parameters
    ----------

    arr : np.ndarray
        Array to check

    Returns
    -------
    int
        Maximum number of consecutive ones in the input array.

    """

    n = len(arr)
    # initialize count
    count = 0
    # initialize max
    result = 0

    for i in range(0, n):
        # If 1 is found, increment count
        # and update result if count
        # becomes more.
        if arr[i] == 1:
            # increase count
            count += 1
            result = max(result, count)
        # Reset count if one is not found
        else:
            count = 0

    return result

In [24]:
%%time
# For each interest period get the maximum number of successive dekads below long term average soil moisture in the interest period.
sm_run_length = []
for interest_period in interest_periods:
    # Get the dekads in the interest period
    ds = da_sm_binned_by_interest_period[interest_period]
    
    # Identify pixels which are empty for all dekads
    no_data_mask = xr.apply_ufunc(
        get_no_data_mask,
        ds,
        input_core_dims=[["dekad"]],
        vectorize=True,
        dask="allowed",
    )
    
    # Get the long term average for the interest period
    long_term_avg = da_sm_long_term_avg_for_ip.sel(dekad=interest_period)
    
    # Get the pixels where the soil moisture is below the long term average soil moisture
    mask = xr.where(ds < long_term_avg, 1, 0)
    
    # Get the maximum number of successive dekads below long term average soil moisture.
    actual_run_length = xr.apply_ufunc(
        max_consecutive_ones,
        mask,
        input_core_dims=[["dekad"]],
        vectorize=True,
        dask="allowed",
    )
    
    # Modify the run length
    modified_run_length = (actual_run_length.max() + 1) - actual_run_length
    modified_run_length = modified_run_length.where(~no_data_mask)
    sm_run_length.append(modified_run_length.assign_coords(dekad=interest_period).expand_dims({"dekad": 1}))

da_sm_actual_run_length = xr.concat(sm_run_length, dim="dekad")
da_sm_actual_run_length

CPU times: user 4.02 s, sys: 28.9 ms, total: 4.04 s
Wall time: 3.99 s

<xarray.DataArray 'L2-RSM-D' (dekad: 230, y: 49, x: 20)>
array([[[nan, nan, nan, ..., nan, nan, nan],
        [nan,  1.,  1., ...,  1.,  1., nan],
        [nan,  1.,  1., ...,  1.,  1., nan],
        ...,
        [nan,  1.,  1., ...,  2.,  1., nan],
        [nan,  1.,  1., ...,  1.,  1., nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan,  1.,  1., ...,  1.,  1., nan],
        [nan,  1.,  1., ...,  1.,  1., nan],
        ...,
        [nan,  1.,  1., ...,  3.,  1., nan],
        [nan,  1.,  1., ...,  1.,  1., nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan,  1.,  1., ...,  1.,  1., nan],
        [nan,  1.,  1., ...,  1.,  1., nan],
        ...,
...
        ...,
        [nan, 17., 19., ..., 16., 12., nan],
        [nan, 17., 17., ..., 11.,  5., nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan,  6.,  7., ..., 15., 13., nan],
        [nan,  9.,  5., ..., 13., 14., nan],
        ...,
        [nan, 16., 18., ..., 15., 11., nan],
        [nan, 16., 16., ..., 10.,  4., nan],
        [nan, nan, nan, ..., nan, nan, nan]],

       [[nan, nan, nan, ..., nan, nan, nan],
        [nan,  6.,  7., ..., 15., 13., nan],
        [nan,  8.,  6., ..., 14., 13., nan],
        ...,
        [nan, 16., 18., ..., 16., 11., nan],
        [nan, 17., 16., ..., 10.,  4., nan],
        [nan, nan, nan, ..., nan, nan, nan]]])
Coordinates:
    spatial_ref  int32 6933
  * y            (y) float64 2.125e+05 2.075e+05 ... -2.25e+04 -2.75e+04
  * x            (x) float64 3.428e+06 3.432e+06 ... 3.518e+06 3.522e+06
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11

## Get the long term average of continous deficit in each interest period

In [25]:
# Get the long term average soil moisture run length for each interest period 
long_term_avg_run_lenth_sm = {}
for dekad_no_in_year, interest_periods_list in grouped_by_year.items():
    long_term_avg_for_period = da_sm_actual_run_length.sel(dekad=interest_periods_list).mean(dim="dekad")
    long_term_avg_run_lenth_sm[dekad_no_in_year] = long_term_avg_for_period
    
da_sm_long_term_avg_run_length_for_ip = xr.concat([long_term_avg_run_lenth_sm[get_dekad_no_in_year(i)].assign_coords(dekad=i).expand_dims({"dekad": 1}) for  i in interest_periods], dim="dekad")
da_sm_long_term_avg_run_length_for_ip

<xarray.DataArray 'L2-RSM-D' (dekad: 230, y: 49, x: 20)>
array([[[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,  9.28571429,  9.71428571, ..., 11.28571429,
         10.42857143,         nan],
        [        nan, 10.28571429,  9.57142857, ..., 11.        ,
          9.85714286,         nan],
        ...,
        [        nan,  9.57142857, 10.        , ...,  9.71428571,
         10.57142857,         nan],
        [        nan, 10.14285714, 10.28571429, ..., 11.14285714,
         11.28571429,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,  9.14285714,  9.57142857, ..., 11.42857143,
         10.28571429,         nan],
        [        nan,  9.85714286,  9.14285714, ..., 10.57142857,
          9.57142857,         nan],
...
        [        nan,  9.71428571,  9.57142857, ..., 10.57142857,
          8.71428571,         nan],
        [        nan,  9.71428571,  9.28571429, ...,  8.28571429,
          9.85714286,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]],

       [[        nan,         nan,         nan, ...,         nan,
                 nan,         nan],
        [        nan,  9.71428571,  8.        , ..., 11.85714286,
         10.57142857,         nan],
        [        nan,  7.85714286, 10.71428571, ..., 10.57142857,
         12.28571429,         nan],
        ...,
        [        nan,  9.85714286,  9.85714286, ..., 11.        ,
          8.42857143,         nan],
        [        nan, 10.        ,  9.57142857, ...,  8.57142857,
          9.71428571,         nan],
        [        nan,         nan,         nan, ...,         nan,
                 nan,         nan]]])
Coordinates:
    spatial_ref  int32 6933
  * y            (y) float64 2.125e+05 2.075e+05 ... -2.25e+04 -2.75e+04
  * x            (x) float64 3.428e+06 3.432e+06 ... 3.518e+06 3.522e+06
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11

## Calculate the scaled Soil Moisture Drought Index

In [26]:
SMDI = (da_sm_actual_avg_for_ip / da_sm_long_term_avg_for_ip) * np.sqrt((da_sm_actual_run_length / da_sm_long_term_avg_run_length_for_ip))
SMDI

<xarray.DataArray 'L2-RSM-D' (dekad: 230, y: 49, x: 20)>
array([[[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan, 0.302827  , 0.29674687, ..., 0.28589231,
         0.27351795,        nan],
        [       nan, 0.27920817, 0.28984816, ..., 0.24668375,
         0.29447778,        nan],
        ...,
        [       nan, 0.2544195 , 0.2758757 , ..., 0.51560642,
         0.27477385,        nan],
        [       nan, 0.25639824, 0.23170484, ..., 0.24205312,
         0.27308586,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan]],

       [[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan, 0.30466965, 0.29709426, ..., 0.28611198,
         0.29135625,        nan],
        [       nan, 0.28461342, 0.28877175, ..., 0.26233911,
         0.31148872,        nan],
...
        [       nan, 1.4745956 , 1.60539394, ..., 1.33868652,
         1.17612415,        nan],
        [       nan, 1.47479266, 1.5367111 , ..., 1.14235749,
         0.54351858,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan]],

       [[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan, 0.73222103, 0.92867195, ..., 1.25849148,
         1.37254628,        nan],
        [       nan, 0.96027505, 0.68106588, ..., 1.30149813,
         1.14325565,        nan],
        ...,
        [       nan, 1.46412871, 1.5804272 , ..., 1.34370373,
         1.19037002,        nan],
        [       nan, 1.5000572 , 1.50377291, ..., 1.11379065,
         0.54802262,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan]]])
Coordinates:
  * y            (y) float64 2.125e+05 2.075e+05 ... -2.25e+04 -2.75e+04
  * x            (x) float64 3.428e+06 3.432e+06 ... 3.518e+06 3.522e+06
    spatial_ref  int32 6933
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11

In [27]:
SMDI_scaled = (SMDI - SMDI.min()) / (SMDI.max() - SMDI.min())
SMDI_scaled

<xarray.DataArray 'L2-RSM-D' (dekad: 230, y: 49, x: 20)>
array([[[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan, 0.05309549, 0.05197208, ..., 0.04996651,
         0.04768014,        nan],
        [       nan, 0.04873151, 0.05069743, ..., 0.04272206,
         0.05155283,        nan],
        ...,
        [       nan, 0.04415137, 0.04811577, ..., 0.09241016,
         0.04791219,        nan],
        [       nan, 0.04451698, 0.03995445, ..., 0.04186647,
         0.0476003 ,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan]],

       [[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan, 0.05343595, 0.05203627, ..., 0.0500071 ,
         0.05097607,        nan],
        [       nan, 0.04973022, 0.05049854, ..., 0.04561465,
         0.05469589,        nan],
...
        [       nan, 0.26959994, 0.29376718, ..., 0.24448839,
         0.21445219,        nan],
        [       nan, 0.26963634, 0.28107685, ..., 0.20821322,
         0.09756741,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan]],

       [[       nan,        nan,        nan, ...,        nan,
                nan,        nan],
        [       nan, 0.13243344, 0.16873113, ..., 0.22967097,
         0.25074457,        nan],
        [       nan, 0.17457035, 0.12298164, ..., 0.23761719,
         0.20837917,        nan],
        ...,
        [       nan, 0.267666  , 0.28915415, ..., 0.24541541,
         0.21708436,        nan],
        [       nan, 0.27430441, 0.27499095, ..., 0.202935  ,
         0.09839961,        nan],
        [       nan,        nan,        nan, ...,        nan,
                nan,        nan]]])
Coordinates:
  * y            (y) float64 2.125e+05 2.075e+05 ... -2.25e+04 -2.75e+04
  * x            (x) float64 3.428e+06 3.432e+06 ... 3.518e+06 3.522e+06
    spatial_ref  int32 6933
  * dekad        (dekad) datetime64[ns] 2018-01-01 2018-01-11 ... 2024-05-11

In [28]:
# Convert to DataFrame.
df = SMDI_scaled.to_dataframe().drop(columns="spatial_ref")
df

                                L2-RSM-D
dekad      y         x
2018-01-01  212500.0 3427500.0       NaN
                     3432500.0       NaN
                     3437500.0       NaN
                     3442500.0       NaN
                     3447500.0       NaN
...                                  ...
2024-05-11 -27500.0  3502500.0       NaN
                     3507500.0       NaN
                     3512500.0       NaN
                     3517500.0       NaN
                     3522500.0       NaN

[225400 rows x 1 columns]

In [29]:
# Convert the DataFrame to an Arrow table
table = Table.from_pandas(df)

# Get the tables existing metadata
existing_meta = table.schema.metadata

# Dump the crs of the DataArray as new metadata to JSON.
meta_json = json.dumps(dict(crs=str(SMDI_scaled.rio.crs)))

# Combine the metadata
combined_meta = {
b"xarray.metadata": meta_json.encode(),
**existing_meta,
}

# Replace the metadata.
table = table.replace_schema_metadata(combined_meta)

In [30]:
# Write the table
write_table(table, output_path, compression="GZIP")